name: Android Studio CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK & NDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build libsnappy-dev

    - name: Grant execute permission to Gradle
      run: chmod +x ./gradlew

    - name: Build project (как в Android Studio)
      run: ./gradlew build --stacktrace --info

    - name: Build APK (релизная сборка)
      run: ./gradlew assembleRelease --stacktrace --info

    - name: Decode and restore keystore
      run: echo "${{ secrets.BUILD_KEY }}" | base64 -d > buildKey.jks

    - name: Sign APK
      run: |
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
        -keystore buildKey.jks \
        app/build/outputs/apk/release/app-release.apk alias_name
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Verify APK signature
      run: jarsigner -verify -verbose -certs app/build/outputs/apk/release/app-release.apk

    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: app-signed-release
        path: app/build/outputs/apk/release/app-release.apk
